# Build the manager binary
ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG VERSION=v0.0.0-devel

FROM docker.io/golang:bookworm AS builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# Copy the go source
COPY api/ api/
COPY cmd/ cmd/
COPY internal/ internal/

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -v -a -ldflags="-X 'github.com/pgvillage-tools/orion/cmd.Version=$VERSION'" -o orion-proxy ./cmd/proxy

FROM docker.io/debian:bookworm-slim

LABEL MAINTAINER=mannemsolutions
WORKDIR /
COPY --from=builder /workspace/orion-proxy ./

ENV ORIONPROXY_CLUSTER_NAME=orion \
    ORIONPROXY_STORE_BACKEND=etcdv3 \
    ORIONPROXY_LISTEN_ADDRESS=0.0.0.0 \
    ORIONPROXY_PORT=25432

EXPOSE 25432

ENTRYPOINT ["/orion-proxy"]
