# Build the manager binary
ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG VERSION=v0.0.0-devel

FROM docker.io/golang:bookworm AS builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum

# Copy the go source
COPY api/ api/
COPY cmd/ cmd/
COPY internal/ internal/
COPY pkg/ pkg/

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -v -a -ldflags="-X 'github.com/pgvillage-tools/orion/cmd.Version=$VERSION'" -o orion ./cmd/cli

FROM docker.io/debian:bookworm-slim

LABEL MAINTAINER=Nibble-IT
WORKDIR /
COPY --from=builder /workspace/orion ./

ENV ORIONCLI_CLUSTER_NAME=orion \
    ORIONCLI_STORE_BACKEND=etcdv3

ENTRYPOINT ["/orion"]
