// Code generated by MockGen. DO NOT EDIT.
// Source: store.go

// Package mock_consensus is a generated GoMock package.
package mock_consensus

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/pgvillage-tools/orion/api/v1"
	consensus "github.com/pgvillage-tools/orion/internal/consensus"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AtomicPutClusterData mocks base method.
func (m *MockStore) AtomicPutClusterData(ctx context.Context, cd *v1.Data, previous *consensus.KVPair) (*consensus.KVPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtomicPutClusterData", ctx, cd, previous)
	ret0, _ := ret[0].(*consensus.KVPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AtomicPutClusterData indicates an expected call of AtomicPutClusterData.
func (mr *MockStoreMockRecorder) AtomicPutClusterData(ctx, cd, previous interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtomicPutClusterData", reflect.TypeOf((*MockStore)(nil).AtomicPutClusterData), ctx, cd, previous)
}

// GetClusterData mocks base method.
func (m *MockStore) GetClusterData(ctx context.Context) (*v1.Data, *consensus.KVPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterData", ctx)
	ret0, _ := ret[0].(*v1.Data)
	ret1, _ := ret[1].(*consensus.KVPair)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetClusterData indicates an expected call of GetClusterData.
func (mr *MockStoreMockRecorder) GetClusterData(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterData", reflect.TypeOf((*MockStore)(nil).GetClusterData), ctx)
}

// GetKeepersInfo mocks base method.
func (m *MockStore) GetKeepersInfo(ctx context.Context) (v1.KeepersInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeepersInfo", ctx)
	ret0, _ := ret[0].(v1.KeepersInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeepersInfo indicates an expected call of GetKeepersInfo.
func (mr *MockStoreMockRecorder) GetKeepersInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeepersInfo", reflect.TypeOf((*MockStore)(nil).GetKeepersInfo), ctx)
}

// GetProxiesInfo mocks base method.
func (m *MockStore) GetProxiesInfo(ctx context.Context) (v1.ProxiesInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxiesInfo", ctx)
	ret0, _ := ret[0].(v1.ProxiesInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxiesInfo indicates an expected call of GetProxiesInfo.
func (mr *MockStoreMockRecorder) GetProxiesInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxiesInfo", reflect.TypeOf((*MockStore)(nil).GetProxiesInfo), ctx)
}

// GetSentinelsInfo mocks base method.
func (m *MockStore) GetSentinelsInfo(ctx context.Context) (v1.SentinelsInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSentinelsInfo", ctx)
	ret0, _ := ret[0].(v1.SentinelsInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSentinelsInfo indicates an expected call of GetSentinelsInfo.
func (mr *MockStoreMockRecorder) GetSentinelsInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSentinelsInfo", reflect.TypeOf((*MockStore)(nil).GetSentinelsInfo), ctx)
}

// Healthy mocks base method.
func (m *MockStore) Healthy(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Healthy indicates an expected call of Healthy.
func (mr *MockStoreMockRecorder) Healthy(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockStore)(nil).Healthy), ctx)
}

// PutClusterData mocks base method.
func (m *MockStore) PutClusterData(ctx context.Context, cd *v1.Data) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutClusterData", ctx, cd)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutClusterData indicates an expected call of PutClusterData.
func (mr *MockStoreMockRecorder) PutClusterData(ctx, cd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutClusterData", reflect.TypeOf((*MockStore)(nil).PutClusterData), ctx, cd)
}

// SetKeeperInfo mocks base method.
func (m *MockStore) SetKeeperInfo(ctx context.Context, id string, ms *v1.KeeperInfo, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetKeeperInfo", ctx, id, ms, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetKeeperInfo indicates an expected call of SetKeeperInfo.
func (mr *MockStoreMockRecorder) SetKeeperInfo(ctx, id, ms, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKeeperInfo", reflect.TypeOf((*MockStore)(nil).SetKeeperInfo), ctx, id, ms, ttl)
}

// SetProxyInfo mocks base method.
func (m *MockStore) SetProxyInfo(ctx context.Context, pi *v1.ProxyInfo, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProxyInfo", ctx, pi, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProxyInfo indicates an expected call of SetProxyInfo.
func (mr *MockStoreMockRecorder) SetProxyInfo(ctx, pi, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProxyInfo", reflect.TypeOf((*MockStore)(nil).SetProxyInfo), ctx, pi, ttl)
}

// SetSentinelInfo mocks base method.
func (m *MockStore) SetSentinelInfo(ctx context.Context, si *v1.SentinelInfo, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSentinelInfo", ctx, si, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSentinelInfo indicates an expected call of SetSentinelInfo.
func (mr *MockStoreMockRecorder) SetSentinelInfo(ctx, si, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSentinelInfo", reflect.TypeOf((*MockStore)(nil).SetSentinelInfo), ctx, si, ttl)
}

// MockElection is a mock of Election interface.
type MockElection struct {
	ctrl     *gomock.Controller
	recorder *MockElectionMockRecorder
}

// MockElectionMockRecorder is the mock recorder for MockElection.
type MockElectionMockRecorder struct {
	mock *MockElection
}

// NewMockElection creates a new mock instance.
func NewMockElection(ctrl *gomock.Controller) *MockElection {
	mock := &MockElection{ctrl: ctrl}
	mock.recorder = &MockElectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElection) EXPECT() *MockElectionMockRecorder {
	return m.recorder
}

// Leader mocks base method.
func (m *MockElection) Leader() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leader")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Leader indicates an expected call of Leader.
func (mr *MockElectionMockRecorder) Leader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leader", reflect.TypeOf((*MockElection)(nil).Leader))
}

// RunForElection mocks base method.
func (m *MockElection) RunForElection(arg0 context.Context) (<-chan bool, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunForElection", arg0)
	ret0, _ := ret[0].(<-chan bool)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// RunForElection indicates an expected call of RunForElection.
func (mr *MockElectionMockRecorder) RunForElection(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunForElection", reflect.TypeOf((*MockElection)(nil).RunForElection), arg0)
}

// Stop mocks base method.
func (m *MockElection) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockElectionMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockElection)(nil).Stop))
}
